#!/usr/bin/env python3
"""Emit filled region outlines for the market-entry map.

The dot raster in worldmap.py is the world. These are the territories that fill
in over it as the sequence plays, so they have to land in exactly the same
projection — this file imports it rather than restating the maths.

Writes regions.py:
  PATHS  {name: svg path string} in the same grid units as DOT_PATH

Source data: Natural Earth 110m admin-0 countries (public domain), plus a
hand-traced outline for the state of Georgia, which an admin-0 file does not
contain. At this scale Georgia is under three grid units wide; the outline is
there to read as one state, not as a survey.
"""

import json
import pathlib
import sys

import worldmap

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "ne_110m_admin_0_countries.geojson"

# Alaska crosses the antimeridian and would draw a band across the whole map;
# the contiguous states are also what "US metros" actually means here.
US_CLIP = (-128.0, 24.0, -66.0, 50.0)

GEORGIA = [
    (-85.61, 34.99),
    (-83.11, 35.00),
    (-83.32, 34.69),
    (-82.21, 33.03),
    (-81.49, 31.12),
    (-81.11, 30.71),
    (-82.04, 30.37),
    (-84.86, 30.64),
    (-85.00, 31.00),
    (-85.11, 32.00),
    (-85.42, 34.00),
    (-85.61, 34.99),
]


def path_for(rings):
    out = []
    for ring in rings:
        pts = [worldmap.project(lon, lat) for lon, lat in ring]
        if len(pts) < 3:
            continue
        head = f"M{pts[0][0]:.2f},{pts[0][1]:.2f}"
        rest = "".join(f"L{x:.2f},{y:.2f}" for x, y in pts[1:])
        out.append(head + rest + "Z")
    return "".join(out)


def clipped(ring, box):
    """Keep a ring only if it lies inside the box. Whole-ring, not per-point:
    clipping vertices would leave the cut edge wandering off the coastline."""
    lo_x, lo_y, hi_x, hi_y = box
    xs = [p[0] for p in ring]
    ys = [p[1] for p in ring]
    return lo_x <= min(xs) and max(xs) <= hi_x and lo_y <= min(ys) and max(ys) <= hi_y


def main():
    if not SRC.exists():
        sys.exit(f"missing {SRC}")
    data = json.loads(SRC.read_text())

    groups = {"usa": [], "africa": [], "korea": []}
    for feature in data["features"]:
        p = feature["properties"]
        name, cont = p.get("NAME"), p.get("CONTINENT")
        if name == "United States of America":
            key, box = "usa", US_CLIP
        elif cont == "Africa":
            key, box = "africa", None
        elif name == "South Korea":
            key, box = "korea", None
        else:
            continue
        for outer, _holes in worldmap_rings(feature["geometry"]):
            if box and not clipped(outer, box):
                continue
            groups[key].append([(c[0], c[1]) for c in outer])

    paths = {k: path_for(v) for k, v in groups.items()}
    paths["georgia"] = path_for([GEORGIA])

    body = ['"""Generated by gen_regions.py — do not edit."""', "", "PATHS = {"]
    for k, v in paths.items():
        body.append(f'    "{k}": "{v}",')
    body.append("}")
    (HERE / "regions.py").write_text("\n".join(body) + "\n")

    for k, v in paths.items():
        print(f"  {k:<8} {len(groups.get(k, [GEORGIA]))} rings, {len(v) / 1024:.1f} KB")


def worldmap_rings(geometry):
    out = []
    if geometry["type"] == "Polygon":
        polys = [geometry["coordinates"]]
    elif geometry["type"] == "MultiPolygon":
        polys = geometry["coordinates"]
    else:
        return out
    for poly in polys:
        if poly:
            out.append((poly[0], poly[1:]))
    return out


if __name__ == "__main__":
    main()
