#!/usr/bin/env python3
"""Rasterise Natural Earth land into a dot-matrix world map for milestone.html.

Emits worldmap.py, imported by gen_pages.py:
  DOT_PATH  — one SVG path string; each dot is a zero-length subpath drawn as a
              round line cap, so thousands of dots cost a single DOM node
  VIEWBOX   — "0 0 W H"; grid columns/rows are the SVG user units, which keeps
              every coordinate a short integer
  project(lon, lat) -> (x, y) in the same units, for placing markers

Projection is Miller cylindrical: equirectangular stretches the high latitudes
badly and Robinson has no closed form worth the trouble here.

Source data: Natural Earth 110m admin-0 countries (public domain).
"""

import json
import math
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "ne_110m_admin_0_countries.geojson"

# Grid resolution. Columns span the full 360°; rows are derived so the cells stay
# square in projected space.
COLS = 210
LAT_MAX = 83.0
LAT_MIN = -56.0  # Antarctica carries no market meaning and eats vertical space

# Landmasses too small to survive this raster anyway, or irrelevant to the map
SKIP = {"Antarctica"}


def miller_y(lat_deg):
    phi = math.radians(lat_deg)
    return 1.25 * math.log(math.tan(math.pi / 4 + 0.4 * phi))


def miller_y_inv(y):
    return math.degrees(2.5 * (math.atan(math.exp(0.8 * y)) - math.pi / 4))


Y_TOP = miller_y(LAT_MAX)
Y_BOT = miller_y(LAT_MIN)
X_SPAN = 2 * math.pi
Y_SPAN = Y_TOP - Y_BOT
ROWS = round(COLS * Y_SPAN / X_SPAN)


def project(lon_deg, lat_deg):
    """Geographic degrees -> grid units matching the dot raster."""
    x = (lon_deg + 180.0) / 360.0 * COLS
    y = (Y_TOP - miller_y(lat_deg)) / Y_SPAN * ROWS
    return x, y


def rings_from(geometry):
    """Flatten a (Multi)Polygon into [(outer, [holes...]), ...]."""
    out = []
    if geometry["type"] == "Polygon":
        polys = [geometry["coordinates"]]
    elif geometry["type"] == "MultiPolygon":
        polys = geometry["coordinates"]
    else:
        return out
    for poly in polys:
        if not poly:
            continue
        out.append((poly[0], poly[1:]))
    return out


def bbox(ring):
    xs = [p[0] for p in ring]
    ys = [p[1] for p in ring]
    return min(xs), min(ys), max(xs), max(ys)


def inside(ring, x, y):
    """Crossing-number test. Ring is a closed list of [lon, lat]."""
    hit = False
    n = len(ring)
    j = n - 1
    for i in range(n):
        xi, yi = ring[i][0], ring[i][1]
        xj, yj = ring[j][0], ring[j][1]
        if (yi > y) != (yj > y):
            if x < (xj - xi) * (y - yi) / (yj - yi) + xi:
                hit = not hit
        j = i
    return hit


def main():
    if not SRC.exists():
        sys.exit(f"missing {SRC} — download ne_110m_admin_0_countries.geojson first")

    data = json.loads(SRC.read_text())

    # (outer, holes, outer_bbox), bucketed by integer longitude so each grid point
    # only tests the rings that can possibly contain it.
    buckets = {}
    for feature in data["features"]:
        if feature["properties"].get("NAME") in SKIP:
            continue
        for outer, holes in rings_from(feature["geometry"]):
            bb = bbox(outer)
            entry = (outer, holes, bb)
            for lon in range(math.floor(bb[0]), math.ceil(bb[2]) + 1):
                buckets.setdefault(lon, []).append(entry)

    dots = []
    for row in range(ROWS):
        y = Y_TOP - (row + 0.5) * Y_SPAN / ROWS
        lat = miller_y_inv(y)
        for col in range(COLS):
            lon = -180.0 + (col + 0.5) * 360.0 / COLS
            for outer, holes, bb in buckets.get(math.floor(lon), ()):
                if not (bb[1] <= lat <= bb[3] and bb[0] <= lon <= bb[2]):
                    continue
                if not inside(outer, lon, lat):
                    continue
                if any(inside(h, lon, lat) for h in holes):
                    continue
                dots.append((col, row))
                break

    path = "".join(f"M{c},{r}h0" for c, r in dots)

    dest = HERE / "worldmap.py"
    dest.write_text(
        '"""Generated by gen_worldmap.py — do not edit."""\n\n'
        "import math\n\n"
        f"COLS = {COLS}\n"
        f"ROWS = {ROWS}\n"
        f"LAT_MAX = {LAT_MAX}\n"
        f"LAT_MIN = {LAT_MIN}\n"
        f'VIEWBOX = "0 0 {COLS} {ROWS}"\n'
        f"Y_TOP = {Y_TOP!r}\n"
        f"Y_SPAN = {Y_SPAN!r}\n\n"
        "\n"
        "def project(lon_deg, lat_deg):\n"
        '    """Geographic degrees -> grid units matching DOT_PATH."""\n'
        "    phi = math.radians(lat_deg)\n"
        "    y = 1.25 * math.log(math.tan(math.pi / 4 + 0.4 * phi))\n"
        "    return (\n"
        "        (lon_deg + 180.0) / 360.0 * COLS,\n"
        "        (Y_TOP - y) / Y_SPAN * ROWS,\n"
        "    )\n\n\n"
        f"DOT_PATH = {path!r}\n"
    )

    print(
        f"grid {COLS}x{ROWS}  dots {len(dots)}  path {len(path)} chars -> {dest.name}"
    )
    for name, lon, lat in [
        ("Seoul", 126.98, 37.57),
        ("Washington DC", -77.04, 38.90),
        ("US centroid", -98.35, 39.50),
        ("Geneva", 6.14, 46.20),
        ("Nairobi", 36.82, -1.29),
    ]:
        x, y = project(lon, lat)
        print(f"  {name:14s} -> {x:7.2f} {y:7.2f}")


if __name__ == "__main__":
    main()
